services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory_db
    ports:
      - "3306:3306"
    environment:
      MY_SQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./data:/var/lib/postgresql/data